import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import Button from "@mui/material/Button";
import { getAccessPermission } from "src/api/musicApi.js";
import MusicChips from "@/stories/MusicChips";
import GenresAutocompleteField from "@/stories/MutilselectGenres";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [token, setToken] = useState("");
  const [genres, setGenres] = useState([]);

  useEffect(() => {
    const hash = window.location.hash;
    let token = window.localStorage.getItem("token");

    if (!token && hash) {
      token = hash
        .substring(1)
        .split("&")
        .find((elem) => elem.startsWith("access_token"))
        .split("=")[1];

      window.location.hash = "";
      window.localStorage.setItem("token", token);
    }

    setToken(token);
  }, [genres]);

  const logout = async () => {
    setToken("");
    window.localStorage.removeItem("token");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}></div>
        {!token ? (
          <Button onClick={getAccessPermission}>Access to spotify</Button>
        ) : (
          <>
            <Button onClick={logout}>Logout</Button>

            <GenresAutocompleteField></GenresAutocompleteField>
          </>
        )}
      </main>
    </>
  );
}
